// Mocks generated by Mockito 5.4.6 from annotations
// in cred_application/test/presentation/bloc/bills_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:cred_application/data/models/bill_section_model.dart' as _i3;
import 'package:cred_application/domain/repository/bills_repository.dart'
    as _i2;
import 'package:cred_application/domain/usecases/get_bills_usecases.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeBillsRepository_0 extends _i1.SmartFake
    implements _i2.BillsRepository {
  _FakeBillsRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBillSectionModel_1 extends _i1.SmartFake
    implements _i3.BillSectionModel {
  _FakeBillSectionModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetBillsUsecases].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetBillsUsecases extends _i1.Mock implements _i4.GetBillsUsecases {
  MockGetBillsUsecases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.BillsRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeBillsRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.BillsRepository);

  @override
  _i5.Future<_i3.BillSectionModel> call(_i4.GetBillsParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.BillSectionModel>.value(
              _FakeBillSectionModel_1(this, Invocation.method(#call, [params])),
            ),
          )
          as _i5.Future<_i3.BillSectionModel>);
}
